import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./assets/css/globals.css";

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`${firaCode.variable} antialiased`}>{children}</body>
    </html>
  );
}
